version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db-anki
    environment:
        POSTGRES_DB: anki_pdf
        POSTGRES_USER: i_konovalov
        POSTGRES_PASSWORD: Flatron0987
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
